# Site wide configuration
title:            Coding Coda
locale:           en_US
url:              http://codingcoda.com
baseurl:          


# Jekyll configuration
lsi:         false
permalink:   /posts/:year/:month/:day/:title/ 
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Default values
defaults:
  -
    scope:
      path: ""
    values:
      image:
        feature: header.jpg
        credit: leventep
        creditlink: http://leventep.deviantart.com/art/abstract-painting-3-421241074
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: [programming]
      comments: true


# Owner Information
owner:
  name: Jason Olson
  avatar: bio-photo.jpg
  bio: "Musician, programmer, husband, and father of two. Full stack developer at Concur. Former PM and Evangelist at Microsoft."
  email:
  disqus-shortname: codingcoda
  rss: http://feeds.feedburner.com/CodingCoda 
  twitter: jolson88
  facebook: jason.olson
  google:
    plus: #username
    analytics: UA-12141067-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jolson88
  stackoverflow: 5418/jason-olson #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jolson88
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: jason-olson
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
