title:            Coding Coda
description:      A musical programmer's journey through the creative
disqus_shortname: codingcoda
url:              http://codingcoda.com

image:
  feature:        header-1.jpg 
  credit:         leventep
  creditlink:     http://leventep.deviantart.com/art/abstract-painting-3-421241074

# Owner/author information
owner:
  name:           Jason Olson
  avatar:         avatar.jpg
  bio:            "Program Manager on Creative Media Experiences in the Operating System Group at MSFT."
  email:          jolson88@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:       jolson88 
  facebook:      jason.olson 
  github:        jolson88 
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics: UA-12141067-1  
#google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:         

highlighter: pygments
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

permalink:   /blog/:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_css: class

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: "post"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
